name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"    # Run every 12 hours (fixed syntax)

  workflow_dispatch:

  push:
    branches:
      - main                   # Changed from master to main (GitHub's default branch name)

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: TSJean45
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: 'Generate Snake'
          add: 'dist'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}